// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.rudtyz.grpcchat.dto;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_IdMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_IdMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_ChatMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_ChatMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_ChatMessageResponse_Hello_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_ChatMessageResponse_Hello_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_ChatMessageResponse_Bye_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_ChatMessageResponse_Bye_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_ChatMessageResponse_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_ChatMessageResponse_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\007message\032\033google/protobuf/e" +
      "mpty.proto\"\027\n\tIdMessage\022\n\n\002id\030\001 \001(\005\"!\n\016M" +
      "essageRequest\022\017\n\007message\030\001 \001(\t\"\211\002\n\023ChatM" +
      "essageResponse\0223\n\005hello\030\001 \001(\0132\".message." +
      "ChatMessageResponse.HelloH\000\022/\n\003bye\030\002 \001(\013" +
      "2 .message.ChatMessageResponse.ByeH\000\0227\n\007" +
      "message\030\003 \001(\0132$.message.ChatMessageRespo" +
      "nse.MessageH\000\032\023\n\005Hello\022\n\n\002id\030\001 \001(\005\032\021\n\003By" +
      "e\022\n\n\002id\030\001 \001(\005\032&\n\007Message\022\n\n\002id\030\001 \001(\005\022\017\n\007" +
      "message\030\002 \001(\tB\003\n\001m2\222\001\n\007Message\022L\n\rClient" +
      "Message\022\027.message.MessageRequest\032\034.messa" +
      "ge.ChatMessageResponse\"\000(\0010\001\0229\n\tClientBy" +
      "e\022\022.message.IdMessage\032\026.google.protobuf." +
      "Empty\"\000B#\n\027org.rudtyz.grpcchat.dtoP\001Z\006.;" +
      "mainb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_message_IdMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_IdMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_IdMessage_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_message_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_MessageRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_message_ChatMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_message_ChatMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_ChatMessageResponse_descriptor,
        new java.lang.String[] { "Hello", "Bye", "Message", "M", });
    internal_static_message_ChatMessageResponse_Hello_descriptor =
      internal_static_message_ChatMessageResponse_descriptor.getNestedTypes().get(0);
    internal_static_message_ChatMessageResponse_Hello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_ChatMessageResponse_Hello_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_message_ChatMessageResponse_Bye_descriptor =
      internal_static_message_ChatMessageResponse_descriptor.getNestedTypes().get(1);
    internal_static_message_ChatMessageResponse_Bye_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_ChatMessageResponse_Bye_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_message_ChatMessageResponse_Message_descriptor =
      internal_static_message_ChatMessageResponse_descriptor.getNestedTypes().get(2);
    internal_static_message_ChatMessageResponse_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_ChatMessageResponse_Message_descriptor,
        new java.lang.String[] { "Id", "Message", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
