// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.rudtyz.grpcchat.dto;

/**
 * Protobuf type {@code message.ChatMessageResponse}
 */
public final class ChatMessageResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:message.ChatMessageResponse)
    ChatMessageResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatMessageResponse.newBuilder() to construct.
  private ChatMessageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatMessageResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatMessageResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChatMessageResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.Builder subBuilder = null;
            if (mCase_ == 1) {
              subBuilder = ((org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello) m_).toBuilder();
            }
            m_ =
                input.readMessage(org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello) m_);
              m_ = subBuilder.buildPartial();
            }
            mCase_ = 1;
            break;
          }
          case 18: {
            org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.Builder subBuilder = null;
            if (mCase_ == 2) {
              subBuilder = ((org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye) m_).toBuilder();
            }
            m_ =
                input.readMessage(org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye) m_);
              m_ = subBuilder.buildPartial();
            }
            mCase_ = 2;
            break;
          }
          case 26: {
            org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.Builder subBuilder = null;
            if (mCase_ == 3) {
              subBuilder = ((org.rudtyz.grpcchat.dto.ChatMessageResponse.Message) m_).toBuilder();
            }
            m_ =
                input.readMessage(org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.rudtyz.grpcchat.dto.ChatMessageResponse.Message) m_);
              m_ = subBuilder.buildPartial();
            }
            mCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.rudtyz.grpcchat.dto.ChatMessageResponse.class, org.rudtyz.grpcchat.dto.ChatMessageResponse.Builder.class);
  }

  public interface HelloOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.ChatMessageResponse.Hello)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code message.ChatMessageResponse.Hello}
   */
  public static final class Hello extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.ChatMessageResponse.Hello)
      HelloOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Hello.newBuilder() to construct.
    private Hello(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hello() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Hello();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Hello(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Hello_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Hello_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.class, org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello)) {
        return super.equals(obj);
      }
      org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello other = (org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello) obj;

      if (getId()
          != other.getId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.ChatMessageResponse.Hello}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.ChatMessageResponse.Hello)
        org.rudtyz.grpcchat.dto.ChatMessageResponse.HelloOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Hello_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Hello_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.class, org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.Builder.class);
      }

      // Construct using org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Hello_descriptor;
      }

      @java.lang.Override
      public org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello getDefaultInstanceForType() {
        return org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.getDefaultInstance();
      }

      @java.lang.Override
      public org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello build() {
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello buildPartial() {
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello result = new org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello) {
          return mergeFrom((org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello other) {
        if (other == org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.ChatMessageResponse.Hello)
    }

    // @@protoc_insertion_point(class_scope:message.ChatMessageResponse.Hello)
    private static final org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello();
    }

    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Hello>
        PARSER = new com.google.protobuf.AbstractParser<Hello>() {
      @java.lang.Override
      public Hello parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hello(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hello> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hello> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ByeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.ChatMessageResponse.Bye)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code message.ChatMessageResponse.Bye}
   */
  public static final class Bye extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.ChatMessageResponse.Bye)
      ByeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Bye.newBuilder() to construct.
    private Bye(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Bye() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Bye();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Bye(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Bye_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Bye_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.class, org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye)) {
        return super.equals(obj);
      }
      org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye other = (org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye) obj;

      if (getId()
          != other.getId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.ChatMessageResponse.Bye}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.ChatMessageResponse.Bye)
        org.rudtyz.grpcchat.dto.ChatMessageResponse.ByeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Bye_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Bye_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.class, org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.Builder.class);
      }

      // Construct using org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Bye_descriptor;
      }

      @java.lang.Override
      public org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye getDefaultInstanceForType() {
        return org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.getDefaultInstance();
      }

      @java.lang.Override
      public org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye build() {
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye buildPartial() {
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye result = new org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye) {
          return mergeFrom((org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye other) {
        if (other == org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.ChatMessageResponse.Bye)
    }

    // @@protoc_insertion_point(class_scope:message.ChatMessageResponse.Bye)
    private static final org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye();
    }

    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Bye>
        PARSER = new com.google.protobuf.AbstractParser<Bye>() {
      @java.lang.Override
      public Bye parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Bye(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Bye> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Bye> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.ChatMessageResponse.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code message.ChatMessageResponse.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.ChatMessageResponse.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.class, org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.rudtyz.grpcchat.dto.ChatMessageResponse.Message)) {
        return super.equals(obj);
      }
      org.rudtyz.grpcchat.dto.ChatMessageResponse.Message other = (org.rudtyz.grpcchat.dto.ChatMessageResponse.Message) obj;

      if (getId()
          != other.getId()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.rudtyz.grpcchat.dto.ChatMessageResponse.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.ChatMessageResponse.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.ChatMessageResponse.Message)
        org.rudtyz.grpcchat.dto.ChatMessageResponse.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.class, org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.Builder.class);
      }

      // Construct using org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_Message_descriptor;
      }

      @java.lang.Override
      public org.rudtyz.grpcchat.dto.ChatMessageResponse.Message getDefaultInstanceForType() {
        return org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.getDefaultInstance();
      }

      @java.lang.Override
      public org.rudtyz.grpcchat.dto.ChatMessageResponse.Message build() {
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.rudtyz.grpcchat.dto.ChatMessageResponse.Message buildPartial() {
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Message result = new org.rudtyz.grpcchat.dto.ChatMessageResponse.Message(this);
        result.id_ = id_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rudtyz.grpcchat.dto.ChatMessageResponse.Message) {
          return mergeFrom((org.rudtyz.grpcchat.dto.ChatMessageResponse.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rudtyz.grpcchat.dto.ChatMessageResponse.Message other) {
        if (other == org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rudtyz.grpcchat.dto.ChatMessageResponse.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.ChatMessageResponse.Message)
    }

    // @@protoc_insertion_point(class_scope:message.ChatMessageResponse.Message)
    private static final org.rudtyz.grpcchat.dto.ChatMessageResponse.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.rudtyz.grpcchat.dto.ChatMessageResponse.Message();
    }

    public static org.rudtyz.grpcchat.dto.ChatMessageResponse.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.rudtyz.grpcchat.dto.ChatMessageResponse.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int mCase_ = 0;
  private java.lang.Object m_;
  public enum MCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    HELLO(1),
    BYE(2),
    MESSAGE(3),
    M_NOT_SET(0);
    private final int value;
    private MCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MCase valueOf(int value) {
      return forNumber(value);
    }

    public static MCase forNumber(int value) {
      switch (value) {
        case 1: return HELLO;
        case 2: return BYE;
        case 3: return MESSAGE;
        case 0: return M_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MCase
  getMCase() {
    return MCase.forNumber(
        mCase_);
  }

  public static final int HELLO_FIELD_NUMBER = 1;
  /**
   * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
   * @return Whether the hello field is set.
   */
  @java.lang.Override
  public boolean hasHello() {
    return mCase_ == 1;
  }
  /**
   * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
   * @return The hello.
   */
  @java.lang.Override
  public org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello getHello() {
    if (mCase_ == 1) {
       return (org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello) m_;
    }
    return org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.getDefaultInstance();
  }
  /**
   * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
   */
  @java.lang.Override
  public org.rudtyz.grpcchat.dto.ChatMessageResponse.HelloOrBuilder getHelloOrBuilder() {
    if (mCase_ == 1) {
       return (org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello) m_;
    }
    return org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.getDefaultInstance();
  }

  public static final int BYE_FIELD_NUMBER = 2;
  /**
   * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
   * @return Whether the bye field is set.
   */
  @java.lang.Override
  public boolean hasBye() {
    return mCase_ == 2;
  }
  /**
   * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
   * @return The bye.
   */
  @java.lang.Override
  public org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye getBye() {
    if (mCase_ == 2) {
       return (org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye) m_;
    }
    return org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.getDefaultInstance();
  }
  /**
   * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
   */
  @java.lang.Override
  public org.rudtyz.grpcchat.dto.ChatMessageResponse.ByeOrBuilder getByeOrBuilder() {
    if (mCase_ == 2) {
       return (org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye) m_;
    }
    return org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.getDefaultInstance();
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  /**
   * <code>.message.ChatMessageResponse.Message message = 3;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return mCase_ == 3;
  }
  /**
   * <code>.message.ChatMessageResponse.Message message = 3;</code>
   * @return The message.
   */
  @java.lang.Override
  public org.rudtyz.grpcchat.dto.ChatMessageResponse.Message getMessage() {
    if (mCase_ == 3) {
       return (org.rudtyz.grpcchat.dto.ChatMessageResponse.Message) m_;
    }
    return org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.getDefaultInstance();
  }
  /**
   * <code>.message.ChatMessageResponse.Message message = 3;</code>
   */
  @java.lang.Override
  public org.rudtyz.grpcchat.dto.ChatMessageResponse.MessageOrBuilder getMessageOrBuilder() {
    if (mCase_ == 3) {
       return (org.rudtyz.grpcchat.dto.ChatMessageResponse.Message) m_;
    }
    return org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mCase_ == 1) {
      output.writeMessage(1, (org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello) m_);
    }
    if (mCase_ == 2) {
      output.writeMessage(2, (org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye) m_);
    }
    if (mCase_ == 3) {
      output.writeMessage(3, (org.rudtyz.grpcchat.dto.ChatMessageResponse.Message) m_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello) m_);
    }
    if (mCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye) m_);
    }
    if (mCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (org.rudtyz.grpcchat.dto.ChatMessageResponse.Message) m_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.rudtyz.grpcchat.dto.ChatMessageResponse)) {
      return super.equals(obj);
    }
    org.rudtyz.grpcchat.dto.ChatMessageResponse other = (org.rudtyz.grpcchat.dto.ChatMessageResponse) obj;

    if (!getMCase().equals(other.getMCase())) return false;
    switch (mCase_) {
      case 1:
        if (!getHello()
            .equals(other.getHello())) return false;
        break;
      case 2:
        if (!getBye()
            .equals(other.getBye())) return false;
        break;
      case 3:
        if (!getMessage()
            .equals(other.getMessage())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (mCase_) {
      case 1:
        hash = (37 * hash) + HELLO_FIELD_NUMBER;
        hash = (53 * hash) + getHello().hashCode();
        break;
      case 2:
        hash = (37 * hash) + BYE_FIELD_NUMBER;
        hash = (53 * hash) + getBye().hashCode();
        break;
      case 3:
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.rudtyz.grpcchat.dto.ChatMessageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rudtyz.grpcchat.dto.ChatMessageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rudtyz.grpcchat.dto.ChatMessageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rudtyz.grpcchat.dto.ChatMessageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rudtyz.grpcchat.dto.ChatMessageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rudtyz.grpcchat.dto.ChatMessageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rudtyz.grpcchat.dto.ChatMessageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rudtyz.grpcchat.dto.ChatMessageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rudtyz.grpcchat.dto.ChatMessageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.rudtyz.grpcchat.dto.ChatMessageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rudtyz.grpcchat.dto.ChatMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rudtyz.grpcchat.dto.ChatMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.rudtyz.grpcchat.dto.ChatMessageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code message.ChatMessageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:message.ChatMessageResponse)
      org.rudtyz.grpcchat.dto.ChatMessageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rudtyz.grpcchat.dto.ChatMessageResponse.class, org.rudtyz.grpcchat.dto.ChatMessageResponse.Builder.class);
    }

    // Construct using org.rudtyz.grpcchat.dto.ChatMessageResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      mCase_ = 0;
      m_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.rudtyz.grpcchat.dto.Chat.internal_static_message_ChatMessageResponse_descriptor;
    }

    @java.lang.Override
    public org.rudtyz.grpcchat.dto.ChatMessageResponse getDefaultInstanceForType() {
      return org.rudtyz.grpcchat.dto.ChatMessageResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.rudtyz.grpcchat.dto.ChatMessageResponse build() {
      org.rudtyz.grpcchat.dto.ChatMessageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.rudtyz.grpcchat.dto.ChatMessageResponse buildPartial() {
      org.rudtyz.grpcchat.dto.ChatMessageResponse result = new org.rudtyz.grpcchat.dto.ChatMessageResponse(this);
      if (mCase_ == 1) {
        if (helloBuilder_ == null) {
          result.m_ = m_;
        } else {
          result.m_ = helloBuilder_.build();
        }
      }
      if (mCase_ == 2) {
        if (byeBuilder_ == null) {
          result.m_ = m_;
        } else {
          result.m_ = byeBuilder_.build();
        }
      }
      if (mCase_ == 3) {
        if (messageBuilder_ == null) {
          result.m_ = m_;
        } else {
          result.m_ = messageBuilder_.build();
        }
      }
      result.mCase_ = mCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.rudtyz.grpcchat.dto.ChatMessageResponse) {
        return mergeFrom((org.rudtyz.grpcchat.dto.ChatMessageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.rudtyz.grpcchat.dto.ChatMessageResponse other) {
      if (other == org.rudtyz.grpcchat.dto.ChatMessageResponse.getDefaultInstance()) return this;
      switch (other.getMCase()) {
        case HELLO: {
          mergeHello(other.getHello());
          break;
        }
        case BYE: {
          mergeBye(other.getBye());
          break;
        }
        case MESSAGE: {
          mergeMessage(other.getMessage());
          break;
        }
        case M_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.rudtyz.grpcchat.dto.ChatMessageResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.rudtyz.grpcchat.dto.ChatMessageResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int mCase_ = 0;
    private java.lang.Object m_;
    public MCase
        getMCase() {
      return MCase.forNumber(
          mCase_);
    }

    public Builder clearM() {
      mCase_ = 0;
      m_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello, org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.Builder, org.rudtyz.grpcchat.dto.ChatMessageResponse.HelloOrBuilder> helloBuilder_;
    /**
     * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
     * @return Whether the hello field is set.
     */
    @java.lang.Override
    public boolean hasHello() {
      return mCase_ == 1;
    }
    /**
     * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
     * @return The hello.
     */
    @java.lang.Override
    public org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello getHello() {
      if (helloBuilder_ == null) {
        if (mCase_ == 1) {
          return (org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello) m_;
        }
        return org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.getDefaultInstance();
      } else {
        if (mCase_ == 1) {
          return helloBuilder_.getMessage();
        }
        return org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.getDefaultInstance();
      }
    }
    /**
     * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
     */
    public Builder setHello(org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello value) {
      if (helloBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        m_ = value;
        onChanged();
      } else {
        helloBuilder_.setMessage(value);
      }
      mCase_ = 1;
      return this;
    }
    /**
     * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
     */
    public Builder setHello(
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.Builder builderForValue) {
      if (helloBuilder_ == null) {
        m_ = builderForValue.build();
        onChanged();
      } else {
        helloBuilder_.setMessage(builderForValue.build());
      }
      mCase_ = 1;
      return this;
    }
    /**
     * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
     */
    public Builder mergeHello(org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello value) {
      if (helloBuilder_ == null) {
        if (mCase_ == 1 &&
            m_ != org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.getDefaultInstance()) {
          m_ = org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.newBuilder((org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello) m_)
              .mergeFrom(value).buildPartial();
        } else {
          m_ = value;
        }
        onChanged();
      } else {
        if (mCase_ == 1) {
          helloBuilder_.mergeFrom(value);
        }
        helloBuilder_.setMessage(value);
      }
      mCase_ = 1;
      return this;
    }
    /**
     * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
     */
    public Builder clearHello() {
      if (helloBuilder_ == null) {
        if (mCase_ == 1) {
          mCase_ = 0;
          m_ = null;
          onChanged();
        }
      } else {
        if (mCase_ == 1) {
          mCase_ = 0;
          m_ = null;
        }
        helloBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
     */
    public org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.Builder getHelloBuilder() {
      return getHelloFieldBuilder().getBuilder();
    }
    /**
     * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
     */
    @java.lang.Override
    public org.rudtyz.grpcchat.dto.ChatMessageResponse.HelloOrBuilder getHelloOrBuilder() {
      if ((mCase_ == 1) && (helloBuilder_ != null)) {
        return helloBuilder_.getMessageOrBuilder();
      } else {
        if (mCase_ == 1) {
          return (org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello) m_;
        }
        return org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.getDefaultInstance();
      }
    }
    /**
     * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello, org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.Builder, org.rudtyz.grpcchat.dto.ChatMessageResponse.HelloOrBuilder> 
        getHelloFieldBuilder() {
      if (helloBuilder_ == null) {
        if (!(mCase_ == 1)) {
          m_ = org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.getDefaultInstance();
        }
        helloBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello, org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello.Builder, org.rudtyz.grpcchat.dto.ChatMessageResponse.HelloOrBuilder>(
                (org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello) m_,
                getParentForChildren(),
                isClean());
        m_ = null;
      }
      mCase_ = 1;
      onChanged();;
      return helloBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye, org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.Builder, org.rudtyz.grpcchat.dto.ChatMessageResponse.ByeOrBuilder> byeBuilder_;
    /**
     * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
     * @return Whether the bye field is set.
     */
    @java.lang.Override
    public boolean hasBye() {
      return mCase_ == 2;
    }
    /**
     * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
     * @return The bye.
     */
    @java.lang.Override
    public org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye getBye() {
      if (byeBuilder_ == null) {
        if (mCase_ == 2) {
          return (org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye) m_;
        }
        return org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.getDefaultInstance();
      } else {
        if (mCase_ == 2) {
          return byeBuilder_.getMessage();
        }
        return org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.getDefaultInstance();
      }
    }
    /**
     * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
     */
    public Builder setBye(org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye value) {
      if (byeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        m_ = value;
        onChanged();
      } else {
        byeBuilder_.setMessage(value);
      }
      mCase_ = 2;
      return this;
    }
    /**
     * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
     */
    public Builder setBye(
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.Builder builderForValue) {
      if (byeBuilder_ == null) {
        m_ = builderForValue.build();
        onChanged();
      } else {
        byeBuilder_.setMessage(builderForValue.build());
      }
      mCase_ = 2;
      return this;
    }
    /**
     * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
     */
    public Builder mergeBye(org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye value) {
      if (byeBuilder_ == null) {
        if (mCase_ == 2 &&
            m_ != org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.getDefaultInstance()) {
          m_ = org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.newBuilder((org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye) m_)
              .mergeFrom(value).buildPartial();
        } else {
          m_ = value;
        }
        onChanged();
      } else {
        if (mCase_ == 2) {
          byeBuilder_.mergeFrom(value);
        }
        byeBuilder_.setMessage(value);
      }
      mCase_ = 2;
      return this;
    }
    /**
     * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
     */
    public Builder clearBye() {
      if (byeBuilder_ == null) {
        if (mCase_ == 2) {
          mCase_ = 0;
          m_ = null;
          onChanged();
        }
      } else {
        if (mCase_ == 2) {
          mCase_ = 0;
          m_ = null;
        }
        byeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
     */
    public org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.Builder getByeBuilder() {
      return getByeFieldBuilder().getBuilder();
    }
    /**
     * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
     */
    @java.lang.Override
    public org.rudtyz.grpcchat.dto.ChatMessageResponse.ByeOrBuilder getByeOrBuilder() {
      if ((mCase_ == 2) && (byeBuilder_ != null)) {
        return byeBuilder_.getMessageOrBuilder();
      } else {
        if (mCase_ == 2) {
          return (org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye) m_;
        }
        return org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.getDefaultInstance();
      }
    }
    /**
     * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye, org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.Builder, org.rudtyz.grpcchat.dto.ChatMessageResponse.ByeOrBuilder> 
        getByeFieldBuilder() {
      if (byeBuilder_ == null) {
        if (!(mCase_ == 2)) {
          m_ = org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.getDefaultInstance();
        }
        byeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye, org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye.Builder, org.rudtyz.grpcchat.dto.ChatMessageResponse.ByeOrBuilder>(
                (org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye) m_,
                getParentForChildren(),
                isClean());
        m_ = null;
      }
      mCase_ = 2;
      onChanged();;
      return byeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Message, org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.Builder, org.rudtyz.grpcchat.dto.ChatMessageResponse.MessageOrBuilder> messageBuilder_;
    /**
     * <code>.message.ChatMessageResponse.Message message = 3;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return mCase_ == 3;
    }
    /**
     * <code>.message.ChatMessageResponse.Message message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public org.rudtyz.grpcchat.dto.ChatMessageResponse.Message getMessage() {
      if (messageBuilder_ == null) {
        if (mCase_ == 3) {
          return (org.rudtyz.grpcchat.dto.ChatMessageResponse.Message) m_;
        }
        return org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.getDefaultInstance();
      } else {
        if (mCase_ == 3) {
          return messageBuilder_.getMessage();
        }
        return org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.getDefaultInstance();
      }
    }
    /**
     * <code>.message.ChatMessageResponse.Message message = 3;</code>
     */
    public Builder setMessage(org.rudtyz.grpcchat.dto.ChatMessageResponse.Message value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        m_ = value;
        onChanged();
      } else {
        messageBuilder_.setMessage(value);
      }
      mCase_ = 3;
      return this;
    }
    /**
     * <code>.message.ChatMessageResponse.Message message = 3;</code>
     */
    public Builder setMessage(
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.Builder builderForValue) {
      if (messageBuilder_ == null) {
        m_ = builderForValue.build();
        onChanged();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }
      mCase_ = 3;
      return this;
    }
    /**
     * <code>.message.ChatMessageResponse.Message message = 3;</code>
     */
    public Builder mergeMessage(org.rudtyz.grpcchat.dto.ChatMessageResponse.Message value) {
      if (messageBuilder_ == null) {
        if (mCase_ == 3 &&
            m_ != org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.getDefaultInstance()) {
          m_ = org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.newBuilder((org.rudtyz.grpcchat.dto.ChatMessageResponse.Message) m_)
              .mergeFrom(value).buildPartial();
        } else {
          m_ = value;
        }
        onChanged();
      } else {
        if (mCase_ == 3) {
          messageBuilder_.mergeFrom(value);
        }
        messageBuilder_.setMessage(value);
      }
      mCase_ = 3;
      return this;
    }
    /**
     * <code>.message.ChatMessageResponse.Message message = 3;</code>
     */
    public Builder clearMessage() {
      if (messageBuilder_ == null) {
        if (mCase_ == 3) {
          mCase_ = 0;
          m_ = null;
          onChanged();
        }
      } else {
        if (mCase_ == 3) {
          mCase_ = 0;
          m_ = null;
        }
        messageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.message.ChatMessageResponse.Message message = 3;</code>
     */
    public org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.Builder getMessageBuilder() {
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.message.ChatMessageResponse.Message message = 3;</code>
     */
    @java.lang.Override
    public org.rudtyz.grpcchat.dto.ChatMessageResponse.MessageOrBuilder getMessageOrBuilder() {
      if ((mCase_ == 3) && (messageBuilder_ != null)) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        if (mCase_ == 3) {
          return (org.rudtyz.grpcchat.dto.ChatMessageResponse.Message) m_;
        }
        return org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.getDefaultInstance();
      }
    }
    /**
     * <code>.message.ChatMessageResponse.Message message = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.rudtyz.grpcchat.dto.ChatMessageResponse.Message, org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.Builder, org.rudtyz.grpcchat.dto.ChatMessageResponse.MessageOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        if (!(mCase_ == 3)) {
          m_ = org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.getDefaultInstance();
        }
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.rudtyz.grpcchat.dto.ChatMessageResponse.Message, org.rudtyz.grpcchat.dto.ChatMessageResponse.Message.Builder, org.rudtyz.grpcchat.dto.ChatMessageResponse.MessageOrBuilder>(
                (org.rudtyz.grpcchat.dto.ChatMessageResponse.Message) m_,
                getParentForChildren(),
                isClean());
        m_ = null;
      }
      mCase_ = 3;
      onChanged();;
      return messageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:message.ChatMessageResponse)
  }

  // @@protoc_insertion_point(class_scope:message.ChatMessageResponse)
  private static final org.rudtyz.grpcchat.dto.ChatMessageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.rudtyz.grpcchat.dto.ChatMessageResponse();
  }

  public static org.rudtyz.grpcchat.dto.ChatMessageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatMessageResponse>
      PARSER = new com.google.protobuf.AbstractParser<ChatMessageResponse>() {
    @java.lang.Override
    public ChatMessageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChatMessageResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChatMessageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatMessageResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.rudtyz.grpcchat.dto.ChatMessageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

