// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.rudtyz.grpcchat.dto;

public interface ChatMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.ChatMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
   * @return Whether the hello field is set.
   */
  boolean hasHello();
  /**
   * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
   * @return The hello.
   */
  org.rudtyz.grpcchat.dto.ChatMessageResponse.Hello getHello();
  /**
   * <code>.message.ChatMessageResponse.Hello hello = 1;</code>
   */
  org.rudtyz.grpcchat.dto.ChatMessageResponse.HelloOrBuilder getHelloOrBuilder();

  /**
   * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
   * @return Whether the bye field is set.
   */
  boolean hasBye();
  /**
   * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
   * @return The bye.
   */
  org.rudtyz.grpcchat.dto.ChatMessageResponse.Bye getBye();
  /**
   * <code>.message.ChatMessageResponse.Bye bye = 2;</code>
   */
  org.rudtyz.grpcchat.dto.ChatMessageResponse.ByeOrBuilder getByeOrBuilder();

  /**
   * <code>.message.ChatMessageResponse.Message message = 3;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.message.ChatMessageResponse.Message message = 3;</code>
   * @return The message.
   */
  org.rudtyz.grpcchat.dto.ChatMessageResponse.Message getMessage();
  /**
   * <code>.message.ChatMessageResponse.Message message = 3;</code>
   */
  org.rudtyz.grpcchat.dto.ChatMessageResponse.MessageOrBuilder getMessageOrBuilder();

  public org.rudtyz.grpcchat.dto.ChatMessageResponse.MCase getMCase();
}
