// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.rudtyz.grpcchat.dto;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_SendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_SendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_SendReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_SendReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_ReceiveReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_ReceiveReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\007message\032\033google/protobuf/e" +
      "mpty.proto\"\036\n\013SendRequest\022\017\n\007message\030\001 \001" +
      "(\t\"\036\n\tSendReply\022\021\n\tmessageId\030\001 \001(\005\"\037\n\014Re" +
      "ceiveReply\022\017\n\007message\030\001 \001(\t2\207\001\n\007Message\022" +
      "8\n\nClientSend\022\024.message.SendRequest\032\022.me" +
      "ssage.SendReply\"\000\022B\n\rClientReceive\022\026.goo" +
      "gle.protobuf.Empty\032\025.message.ReceiveRepl" +
      "y\"\0000\001B#\n\027org.rudtyz.grpcchat.dtoP\001Z\006.;ma" +
      "inb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_message_SendRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_SendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_SendRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_message_SendReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_SendReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_SendReply_descriptor,
        new java.lang.String[] { "MessageId", });
    internal_static_message_ReceiveReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_message_ReceiveReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_ReceiveReply_descriptor,
        new java.lang.String[] { "Message", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
