// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.rudtyz.grpcchat.dto;

public interface IdMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.IdMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
