// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.rudtyz.grpcchat.dto;

public interface SendRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.SendRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
