// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.rudtyz.grpcchat.dto;

public interface SendReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.SendReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 messageId = 1;</code>
   * @return The messageId.
   */
  int getMessageId();
}
